# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # path to the private key
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # path to the public key
    pass_phrase: 'tChP_-nveA_r8lRqtHvB-uh-BBArsR9w5SyBpW4NMec' # your passphrase
    token_ttl: 3600                                           # token time to live in seconds
