controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml

task:
    path: /task
    controller: App\Controller\Task\TaskController
    methods: [ GET ]
    options:
        expose: true

task-store:
    path: /task-store
    controller: App\Controller\Task\TaskStoreController
    methods: [ POST ]
    options:
        expose: true
task-delete:
    path: /task-delete
    controller: App\Controller\Task\TaskDeleteController
    methods: [ POST ]
    options:
        expose: true

add-user:
    path: /register
    controller: App\Controller\User\RegistrationController
    methods: [ POST ]
    options:
        expose: true

app_logout:
    path: /logout
    methods: GET


product:
    path: /product
    controller: App\Controller\Product\ProductController
    methods: [ GET ]
    options:
        expose: true

product-store:
    path: /product-store
    controller: App\Controller\Product\ProductStoreController
    methods: [ POST ]
    options:
        expose: true

product-delete:
    path: /product-delete
    controller: App\Controller\Product\ProductDeleteController
    methods: [ POST ]
    options:
        expose: true

category:
    path: /category
    controller: App\Controller\Category\CategoryController
    methods: [ GET ]
    options:
        expose: true

category-store:
    path: /category-store
    controller: App\Controller\Category\CategoryStoreController
    methods: [ POST ]
    options:
        expose: true

article:
    path: /article
    controller: App\Controller\Article\ArticleController
    methods: [ GET ]
    options:
        expose: true

article-store:
    path: /article-store
    controller: App\Controller\Article\ArticleStoreController
    methods: [ POST ]
    options:
        expose: true

login:
    path: /login
    controller: App\Security\SecurityController
    methods: [ POST ]
    options:
        expose: true
